gh-106: Add MyPy into the CI
Also we fix all the errors because we cannot silence them for later.
For function parameter and return types in the standard Python library
we use <https://github.com/python/typeshed/tree/b98b6c37/stdlib>.

Here is the full list for `python -mmypy github_readme`:

```plain
github_readme\regen_readme.py:53: error: "Pattern[Any]" has no attribute "group"; maybe "groups"?  [attr-defined]
github_readme\regen_readme.py:58: error: Argument 1 to "Contribution" has incompatible type "Callable[[], Any | str | NestedDict[str] | int]"; expected "Callable[[], int]"  [arg-type]
github_readme\regen_readme.py:58: error: Item "str" of "str | NestedDict[str]" has no attribute "get"  [union-attr]
github_readme\regen_readme.py:58: error: Incompatible return value type (got "Any | str | NestedDict[str] | int", expected "int")  [return-value]
github_readme\regen_readme.py:63: error: Argument 1 to "Contribution" has incompatible type "Callable[[], Any | str | NestedDict[str] | int]"; expected "Callable[[], int]"  [arg-type]
github_readme\regen_readme.py:63: error: Item "str" of "str | NestedDict[str]" has no attribute "get"  [union-attr]
github_readme\regen_readme.py:63: error: Incompatible return value type (got "Any | str | NestedDict[str] | int", expected "int")  [return-value]
github_readme\regen_readme.py:68: error: Argument 1 to "Contribution" has incompatible type "Callable[[], Any | str | NestedDict[str] | int]"; expected "Callable[[], int]"  [arg-type]
github_readme\regen_readme.py:68: error: Item "str" of "str | NestedDict[str]" has no attribute "get"  [union-attr]
github_readme\regen_readme.py:68: error: Incompatible return value type (got "Any | str | NestedDict[str] | int", expected "int")  [return-value]
github_readme\collect_contribs.py:50: error: Incompatible return value type (got "tuple[Any, str, Any, Any]", expected "tuple[str, str, str]")  [return-value]
github_readme\collect_contribs.py:117: error: Incompatible return value type (got "tuple[str, str, Any]", expected "tuple[str, list[str], NestedDict[str]]")  [return-value]
github_readme\collect_contribs.py:126: error: "list[str]" has no attribute "items"  [attr-defined]
github_readme\collect_contribs.py:127: error: Invalid index type "str" for "str"; expected type "SupportsIndex | slice[Any, Any, Any]"  [index]
github_readme\collect_contribs.py:128: error: Unsupported target for indexed assignment ("str | NestedDict[str]")  [index]
github_readme\collect_contribs.py:128: error: Dict entry 0 has incompatible type "str": "int"; expected "str": "str | NestedDict[str]"  [dict-item]
github_readme\collect_contribs.py:130: error: Incompatible types in assignment (expression has type "dict[str, str | NestedDict[str]]", target has type "str")  [assignment]
github_readme\collect_contribs.py:131: error: Invalid index type "str" for "str"; expected type "SupportsIndex | slice[Any, Any, Any]"  [index]
github_readme\collect_contribs.py:132: error: Invalid index type "str" for "str"; expected type "SupportsIndex | slice[Any, Any, Any]"  [index]
github_readme\collect_contribs.py:133: error: Invalid index type "str" for "str"; expected type "SupportsIndex | slice[Any, Any, Any]"  [index]
github_readme\collect_contribs.py:149: error: Need more than 3 values to unpack (4 expected)  [misc]
github_readme\collect_contribs.py:150: error: Argument 1 to "_make_query" has incompatible type "tuple[dict[str, str], str]"; expected "dict[str, str]"  [arg-type]
github_readme\collect_contribs.py:151: error: Argument 2 to "_output_results" has incompatible type "TextIO | Any"; expected "TextIOBase"  [arg-type]
Found 23 errors in 2 files (checked 2 source files)
```