Add the diagnostics of `build` directory creation
We did nit expect it so check what step creates it and copies all Python
scripts here confusing MyPy:

```plain
github_readme/collect_contribs.py: error: Duplicate module named "collect_contribs" (also at "github_readme/build/lib/collect_contribs.py")
github_readme/collect_contribs.py: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#mapping-file-paths-to-modules for more info
github_readme/collect_contribs.py: note: Common resolutions include: a) using `--exclude` to avoid checking one of them, b) adding `__init__.py` somewhere, c) using `--explicit-package-bases` or adjusting MYPYPATH
Found 1 error in 1 file (errors prevented further checking)
Error: Process completed with exit code 2.
```