Fix license info to the PEP-639 formar
> setuptools.errors.InvalidConfigError: License classifiers have been
> superseded by license expressions
> (see https://peps.python.org/pep-0639/). Please remove:
>
> License :: OSI Approved :: MIT License

So we leave `project.license` as the only license field.