Add a version field generated from a commit ID
> ValueError: invalid pyproject.toml config: `project`.
> configuration error: `project` must contain ['version'] properties

I believed that private projects are not required to have an assigned
version. The version field is, indeed, not optional and strictly
checked.

So we add some release version that will never increase because there is
no public release.