Remove the package build directory
The error spotted earlier in this PR:

```plain
github_readme/collect_contribs.py: error: Duplicate module named "collect_contribs" (also at "github_readme/build/lib/collect_contribs.py")
github_readme/collect_contribs.py: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#mapping-file-paths-to-modules for more info
github_readme/collect_contribs.py: note: Common resolutions include: a) using `--exclude` to avoid checking one of them, b) adding `__init__.py` somewhere, c) using `--explicit-package-bases` or adjusting MYPYPATH
Found 1 error in 1 file (errors prevented further checking)
Error: Process completed with exit code 2.
```

is caused by the output of `pip install ./github_readme`. So we remove
the output because we need not the package itself but its dependencies.

We leave the build process itself to catch build errors.